# Travis CI configuration for coverage testing
language: c
# sudo: false # only for faster builds
# os: osx
dist: bionic

# Compiler selection
compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade
  - sudo apt-get -qq autoremove
  - sudo apt-get -qq install aspell aspell-en valgrind
  - wget --quiet https://media.githubusercontent.com/media/bernardosulzbach/bigword/master/data/en/books/a-tale-of-two-cities.txt

install:
  - cd ${TRAVIS_BUILD_DIR}
  - aspell dump master > wordlist.txt

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "Building assignment now!"

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "Automated build and testing completed!"
